lessons:
  outputs:
    dev:
      dataset: dbt_jfk
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: reference-clock-420208
      threads: 60
      type: bigquery

    testing:
      dataset: dbt_test
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: reference-clock-420208
      threads: 60
      type: bigquery
  target: dev